### ISSUE TITLE
Apps are selectable

### ISSUE THREAD

**Issue by oldmartijntje** [oldmartijntje/oldmartijntje.nl-client#75]
on [this](https://oldmartijntje.nl/Homepage) page.

You can hold the mouse on an app, and select an page, this should be made unselectable

```css
.unselectable {
  user-select: none;
}
```
